create table if not exists public.profiles (id bigint generated by default as identity primary key,name text not null default 'Marlon Armado',role text not null default 'System Developer',headline text not null default 'Full-Stack Developer',bio text,location text default 'Philippines',availability text default 'Available',email text,github_url text,linkedin_url text,avatar_url text,updated_at timestamptz default now());
create table if not exists public.projects (id bigint generated by default as identity primary key,title text not null,slug text unique,description text,technologies text[] default '{}',status text default 'LIVE',image_url text,github_url text,demo_url text,featured boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.skills (id bigint generated by default as identity primary key,category text not null,name text not null,level integer default 80 check(level between 0 and 100),sort_order integer default 0);
create table if not exists public.experience (id bigint generated by default as identity primary key,company text not null,position text not null,start_date date,end_date date,description text,sort_order integer default 0);
create table if not exists public.services (id bigint generated by default as identity primary key,title text not null,description text,sort_order integer default 0);
create table if not exists public.inquiries (id bigint generated by default as identity primary key,name text not null,email text not null,subject text,message text not null,status text default 'NEW',created_at timestamptz default now());
create table if not exists public.site_visits (id bigint generated by default as identity primary key, visited_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.projects enable row level security; alter table public.skills enable row level security; alter table public.experience enable row level security; alter table public.services enable row level security; alter table public.inquiries enable row level security;
create policy "Public read profiles" on public.profiles for select to anon,authenticated using(true);
create policy "Public read projects" on public.projects for select to anon,authenticated using(true);
create policy "Public read skills" on public.skills for select to anon,authenticated using(true);
create policy "Public read experience" on public.experience for select to anon,authenticated using(true);
create policy "Public read services" on public.services for select to anon,authenticated using(true);
create policy "Anyone can submit inquiry" on public.inquiries for insert to anon,authenticated with check(true);

alter table public.site_visits enable row level security;
create or replace function public.record_site_visit()
returns bigint language plpgsql security definer set search_path = public
as $$ declare total bigint; begin
  insert into public.site_visits default values;
  select count(*) into total from public.site_visits;
  return total;
end; $$;
revoke all on function public.record_site_visit() from public;
grant execute on function public.record_site_visit() to anon, authenticated;


-- Starter data based on the supplied Marlon Armado portfolio.
insert into public.profiles (name,role,headline,bio,location,availability) select 'Marlon Armado','System Developer','Full-Stack Developer','I am a Web and Mobile Developer with experience building responsive websites and cross-platform mobile applications. I specialize in turning ideas into functional, user-friendly digital solutions. I enjoy solving problems, writing clean code, and continuously learning to improve performance and user experience.','Philippines','Available for freelance and full-time work' where not exists (select 1 from public.profiles);
insert into public.projects (title,description,technologies,status,image_url,featured) select * from (values ('Human Resources Management System','A centralized web-based platform for employee records, attendance tracking, leave filing, payroll-ready reporting, and HR workflow management.',array['PHP','MySQL','JavaScript'],'LIVE','/projects/hr1.jfif',true),('Car Rental and Transport System','A booking and fleet management solution for vehicle reservations, trip scheduling, availability checks, customer records, and transport dispatch operations.',array['PHP','MySQL','JavaScript'],'LIVE','/projects/car1.jfif',true),('Barangay Management System','A digital barangay operations platform for resident profiling, certificate and clearance requests, records management, reporting, and streamlined community service workflows.',array['PHP','MySQL','JavaScript'],'LIVE','/projects/brgy1.jpg',true)) as v(title,description,technologies,status,image_url,featured) where not exists (select 1 from public.projects);
insert into public.skills (category,name,level,sort_order) select * from (values ('FRONTEND','HTML',88,1),('FRONTEND','CSS',84,2),('FRONTEND','JavaScript',85,3),('BACKEND','PHP',93,4),('DATABASE','MySQL',86,5),('MOBILE','React Native',91,6)) as v(category,name,level,sort_order) where not exists (select 1 from public.skills);
insert into public.services (title,description,sort_order) select * from (values ('Custom Web Development','Design and development of responsive, high-performance websites tailored to your business goals and user needs.',1),('UI/UX Design','Creation of clean, user-focused interfaces that improve usability, strengthen brand presence, and enhance customer experience.',2),('Performance Optimization','Technical improvements for speed, SEO readiness, and overall site performance to support better visibility and engagement.',3),('Mobile App Development','Cross-platform mobile application development focused on reliable functionality, smooth interaction, and maintainable code.',4),('API Integration','Integration of third-party and custom APIs to connect systems, automate workflows, and enable scalable digital solutions.',5),('Maintenance & Support','Ongoing updates, bug fixes, and technical support to keep your web and mobile products secure, stable, and up to date.',6)) as v(title,description,sort_order) where not exists (select 1 from public.services);
