-- Run this migration by itself in Supabase SQL Editor.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now()
);

alter table public.site_visits enable row level security;

create or replace function public.record_site_visit()
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  total bigint;
begin
  insert into public.site_visits default values;
  select count(*) into total from public.site_visits;
  return total;
end;
$function$;

revoke all on function public.record_site_visit() from public;
grant execute on function public.record_site_visit() to anon, authenticated;
